services:
  postgres:
    image: postgres:16
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: origin-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "49951:50051"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Minimal configuration for local development
      # Production values are loaded from AWS Parameter Store
      - ENVIRONMENT=local
      - AWS_REGION=us-east-1
      - SERVICE_NAME=backend
    networks:
      - app-network

  envoy:
    hostname: envoy
    image: origin-envoy
    build:
      context: ./backend/envoy
      dockerfile: Dockerfile
    ports:
      - "49999:8080"
    networks:
      - app-network

  frontend:
    image: origin-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # Frontend only needs the backend URL for API calls
      - NEXT_PUBLIC_BACKEND_URL=http://envoy:8080
    networks:
      - app-network

  storybook:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: builder
    ports:
      - "6006:6006"
    command: npm run storybook
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/.storybook:/app/.storybook
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

