# -*- mode: Python -*-

# Load docker-compose
docker_compose('./docker-compose.yml')

# Define resources for each service
dc_resource('postgres', labels=["database"])
dc_resource('redis', labels=["database"])
dc_resource('backend', labels=["backend"], resource_deps=['postgres', 'redis'])
dc_resource('envoy', labels=["proxy"], resource_deps=['backend'])

# Watch for changes in the backend
watch_file('./backend/src')
watch_file('./backend/proto')
watch_file('./backend/Cargo.toml')
watch_file('./backend/build.rs')

# Watch for changes in the frontend
watch_file('./frontend/src')
watch_file('./frontend/package.json')
watch_file('./frontend/next.config.js')

# TypeScript types are now generated by the backend's build.rs
# No need for a separate step here as it's part of the backend build process

# Print helpful message
print("""
Template project is running!
----------------------------
Frontend: http://localhost:3000
Storybook: http://localhost:6006/ui
Backend gRPC: localhost:50051
Envoy Proxy (HTTP to gRPC): http://localhost:49999
Postgres: localhost:5432
Redis: localhost:6379
""")
