# Cargo configuration for optimized builds
[build]
# Use all available cores (auto-detect)
# jobs = 0 is not valid, removing this line

# Use sparse registry protocol for faster dependency resolution
[registries.crates-io]
protocol = "sparse"

# Network optimizations
[net]
git-fetch-with-cli = true

# Target-specific optimizations
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "codegen-units=1",     # Better optimization for release builds
    "-C", "target-cpu=generic",  # Portable but optimized
]

[target.x86_64-apple-darwin] 
rustflags = [
    "-C", "codegen-units=16",    # More parallel codegen for dev builds
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "codegen-units=16",    # More parallel codegen for dev builds  
]

# Environment variables for build optimization
[env]
# Enable incremental compilation for development
CARGO_INCREMENTAL = "1"
# Use sparse registry protocol
CARGO_REGISTRIES_CRATES_IO_PROTOCOL = "sparse"
# Optimize git fetching
CARGO_NET_GIT_FETCH_WITH_CLI = "true"