[build]
# Use faster linker (disabled for macOS compatibility)
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
# Enable parallel codegen and optimizations
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
]

[profile.release]
# Optimize for speed and size
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
# Faster compilation for development
opt-level = 0
debug = true
strip = false